const cfg=window.GYM_CONFIG??{};
const configured=cfg.SUPABASE_URL&&cfg.SUPABASE_ANON_KEY&&!cfg.SUPABASE_URL.includes("YOUR_PROJECT");
const $=(s)=>document.querySelector(s); const $$=(s)=>[...document.querySelectorAll(s)];
const el={setup:$("#setup-screen"),auth:$("#auth-screen"),app:$("#app-screen"),authForm:$("#auth-form"),authMessage:$("#auth-message"),athletes:$("#athlete-switcher"),group:$("#group-filter"),search:$("#exercise-search"),list:$("#results-list"),detailEmpty:$("#detail-empty"),detail:$("#detail-content"),drawer:$("#record-drawer"),backdrop:$("#drawer-backdrop"),toast:$("#toast"),recordAthletes:$("#record-athletes"),recordExercises:$("#record-exercises"),recordMessage:$("#record-message"),exerciseDialog:$("#exercise-dialog"),exerciseForm:$("#exercise-form"),exerciseMessage:$("#exercise-message")};
const state={athletes:[],exercises:[],sets:[],athlete:null,exerciseId:null,chart:null,recordDay:null,recordExercise:null,recordAthlete:null,seeded:false};
let db;
const previewMode=new URLSearchParams(location.search).has("preview")&&["localhost","127.0.0.1"].includes(location.hostname);

function show(screen){el.setup.classList.toggle("hidden",screen!=="setup");el.auth.classList.toggle("hidden",screen!=="auth");el.app.classList.toggle("hidden",screen!=="app")}
function message(node,text="",error=false){node.textContent=text;node.classList.toggle("error",error)}
function escapeHtml(v=""){return String(v).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
function dateLabel(v,short=false){return new Intl.DateTimeFormat("ru-RU",short?{day:"2-digit",month:"short"}:{day:"2-digit",month:"short",year:"numeric"}).format(new Date(v))}
function imageFor(exercise){return `./assets/exercises/${exercise.image_slug||"leg-curl"}.png`}
function dayForGroup(group){return ["Ноги","Корпус"].includes(group)?"Ноги":"Спина"}
function imageSlugForGroup(group){return ({Ноги:"leg-press",Корпус:"ab-crunch",Спина:"seated-row",Грудь:"incline-dumbbell-press",Плечи:"smith-shoulder-press",Трапеции:"shrugs"})[group]||"leg-curl"}
function resultLabel(set){const value=set.assistance_kg!=null?Number(set.assistance_kg):Number(set.weight_kg);return `${String(value).replace("-","−")} × ${set.reps}`}
function personSets(){return state.sets.filter(s=>s.athletes?.slug===state.athlete)}
function sortedHistory(exerciseId){return personSets().filter(s=>s.exercise_id===exerciseId).sort((a,b)=>new Date(a.workouts.performed_at)-new Date(b.workouts.performed_at))}
function latestByExercise(){const map=new Map();[...personSets()].sort((a,b)=>new Date(b.workouts.performed_at)-new Date(a.workouts.performed_at)).forEach(s=>{if(!map.has(s.exercise_id))map.set(s.exercise_id,s)});return [...map.values()]}
function showToast(text){el.toast.textContent=text;el.toast.classList.remove("hidden");setTimeout(()=>el.toast.classList.add("hidden"),2600)}
function applyAthleteTheme(){const isNatasha=state.athlete==="natasha";[el.app,document.body].forEach(node=>{node.classList.toggle("theme-natasha",isNatasha);node.classList.toggle("theme-artem",!isNatasha)});document.documentElement.style.colorScheme="light"}

async function ensureSeed(){
  if(state.athletes.length||!window.GYM_SEED)return;
  const aRes=await db.from("athletes").insert(window.GYM_SEED.athletes).select("id,slug,name"); if(aRes.error)throw aRes.error;
  const unique=new Map();window.GYM_SEED.records.forEach(r=>unique.set(r[4],{name:r[3],muscle_group:r[2],image_slug:r[4]}));
  const eRes=await db.from("exercises").insert([...unique.values()]).select("id,name,muscle_group,image_slug");if(eRes.error)throw eRes.error;
  const athleteIds=Object.fromEntries(aRes.data.map(a=>[a.slug,a.id]));const exerciseIds=Object.fromEntries(eRes.data.map(e=>[e.image_slug,e.id]));
  for(const date of [...new Set(window.GYM_SEED.records.map(r=>r[0]))]){
    const records=window.GYM_SEED.records.filter(r=>r[0]===date);const dayType=date==="2026-08-24"?"Спина":"Ноги";
    const wRes=await db.from("workouts").insert({performed_at:`${date}T12:00:00+02:00`,day_type:dayType,notes:"Импортировано из тренировочной базы"}).select("id").single();if(wRes.error)throw wRes.error;
    const rows=records.map((r,i)=>({workout_id:wRes.data.id,athlete_id:athleteIds[r[1]],exercise_id:exerciseIds[r[4]],set_order:i+1,weight_kg:r[5]??0,assistance_kg:r[6],reps:r[7],is_warmup:false,next_step:r[9],comment:r[10]||null}));
    const sRes=await db.from("workout_sets").insert(rows);if(sRes.error)throw sRes.error;
  }
  state.seeded=true;
}

async function loadData(){
  const [a,e,s]=await Promise.all([
    db.from("athletes").select("id,slug,name").order("name"),
    db.from("exercises").select("id,name,muscle_group,image_slug").order("name"),
    db.from("workout_sets").select("id,workout_id,athlete_id,exercise_id,set_order,weight_kg,assistance_kg,reps,next_step,comment,workouts(id,performed_at,day_type),athletes(id,slug,name),exercises(id,name,muscle_group,image_slug)")
  ]);if(a.error)throw a.error;if(e.error)throw e.error;if(s.error)throw s.error;
  state.athletes=a.data??[];state.exercises=e.data??[];state.sets=(s.data??[]).filter(x=>x.athletes&&x.exercises&&x.workouts);
  if(!state.athletes.length){await ensureSeed();return loadData()}
  state.athlete=state.athlete&&state.athletes.some(a=>a.slug===state.athlete)?state.athlete:(state.athletes.find(a=>a.slug==="artem")?.slug||state.athletes[0].slug);
  if(!state.exerciseId)state.exerciseId=latestByExercise()[0]?.exercise_id||null;render();
}

function renderAthletes(){applyAthleteTheme();const html=state.athletes.map(a=>`<button class="${a.slug===state.athlete?"active":""}" data-athlete="${a.slug}" type="button">${escapeHtml(a.name)}</button>`).join("");el.athletes.innerHTML=html;el.recordAthletes.innerHTML=state.athletes.map(a=>`<button class="${a.slug===state.recordAthlete?"active":""}" data-record-athlete="${a.slug}" type="button">${escapeHtml(a.name)}</button>`).join("");$$('[data-athlete]').forEach(b=>b.onclick=()=>{state.athlete=b.dataset.athlete;state.exerciseId=latestByExercise()[0]?.exercise_id||null;render()});$$('[data-record-athlete]').forEach(b=>b.onclick=()=>{state.recordAthlete=b.dataset.recordAthlete;renderAthletes()})}
function changeLabel(history){if(history.length<2)return {text:"Первая запись",kind:"wait",icon:"horizontal_rule"};const prev=history.at(-2),last=history.at(-1);const prevLoad=prev.assistance_kg??prev.weight_kg,lastLoad=last.assistance_kg??last.weight_kg;if(Number(lastLoad)!==Number(prevLoad)){const delta=Number(lastLoad)-Number(prevLoad);return {text:`${delta>0?"+":""}${String(delta).replace("-","−")} кг`,kind:"good",icon:"trending_up"}}const delta=last.reps-prev.reps;return delta>0?{text:`+${delta} повт.`,kind:"good",icon:"trending_up"}:{text:"Без изменений",kind:"wait",icon:"trending_flat"}}
function renderFilters(){const groups=[...new Set(state.exercises.map(e=>e.muscle_group).filter(Boolean))].sort();const current=el.group.value;el.group.innerHTML='<option value="all">Все группы</option>'+groups.map(g=>`<option value="${escapeHtml(g)}">${escapeHtml(g)}</option>`).join("");el.group.value=groups.includes(current)?current:"all"}
function renderList(){let rows=latestByExercise();const q=el.search.value.trim().toLowerCase(),group=el.group.value;rows=rows.filter(s=>(group==="all"||s.exercises.muscle_group===group)&&(!q||s.exercises.name.toLowerCase().includes(q)));if(!rows.length){el.list.innerHTML='<div class="empty-list">Нет результатов по выбранному фильтру</div>';return}el.list.innerHTML=rows.map(s=>{const h=sortedHistory(s.exercise_id),delta=changeLabel(h);return `<button class="result-row ${s.exercise_id===state.exerciseId?"selected":""}" data-exercise="${s.exercise_id}" type="button"><span class="exercise-cell"><img src="${imageFor(s.exercises)}" alt="${escapeHtml(s.exercises.name)}"><span class="exercise-copy"><strong>${escapeHtml(s.exercises.name)}</strong><small>${escapeHtml(s.exercises.muscle_group||"")}</small></span></span><span class="primary-result">${resultLabel(s)}</span><span>${dateLabel(s.workouts.performed_at,true)}</span><span class="target">${escapeHtml(s.next_step||"Повторить результат")}</span><span class="delta ${delta.kind}"><span class="material-symbols-rounded">${delta.icon}</span>${delta.text}</span></button>`}).join("");$$('[data-exercise]').forEach(b=>b.onclick=()=>{state.exerciseId=b.dataset.exercise;renderList();renderDetail();if(matchMedia("(max-width: 980px)").matches){el.app.classList.add("detail-open");$("#detail-pane").classList.add("mobile-open");document.body.style.overflow="hidden"}})}
function closeDetail(){$("#detail-pane").classList.remove("mobile-open");el.app.classList.remove("detail-open");document.body.style.overflow=""}
function renderDetail(){const history=sortedHistory(state.exerciseId);if(!history.length){el.detailEmpty.classList.remove("hidden");el.detail.classList.add("hidden");return}el.detailEmpty.classList.add("hidden");el.detail.classList.remove("hidden");const latest=history.at(-1),first=history[0],exercise=latest.exercises,assisted=history.some(s=>s.assistance_kg!=null);const score=s=>assisted?Math.max(0,200-Number(s.assistance_kg??0))*Number(s.reps):Number(s.weight_kg)*Number(s.reps);const firstScore=score(first),progress=firstScore?Math.round((score(latest)-firstScore)/firstScore*100):0;$("#detail-group").textContent=exercise.muscle_group||"Упражнение";$("#detail-name").textContent=exercise.name;$("#detail-result").textContent=resultLabel(latest);$("#detail-date").textContent=dateLabel(latest.workouts.performed_at);$("#detail-target").textContent=latest.next_step||"Повторить результат";$("#detail-progress").textContent=`${progress>0?"+":""}${progress}%`;$("#detail-progress").className=progress>0?"positive":"";$("#detail-sessions").textContent=`${history.length} ${history.length===1?"запись":"записей"}`;$("#history-list").innerHTML=[...history].reverse().map(s=>`<div class="history-row"><span>${dateLabel(s.workouts.performed_at,true)}</span><strong>${resultLabel(s)}</strong><small>${escapeHtml(s.comment||s.next_step||"")}</small></div>`).join("");if(state.chart)state.chart.destroy();const primary=state.athlete==="natasha"?"#c52d64":"#2e6687",secondary=state.athlete==="natasha"?"#8c6cc7":"#7a8993";state.chart=new Chart($("#progress-chart"),{type:"line",data:{labels:history.map(s=>dateLabel(s.workouts.performed_at,true)),datasets:[{label:assisted?"Помощь, кг":"Вес, кг",data:history.map(s=>Number(s.assistance_kg??s.weight_kg)),borderColor:primary,backgroundColor:primary,tension:.25,yAxisID:"y",pointRadius:4},{label:"Повторы",data:history.map(s=>s.reps),borderColor:secondary,backgroundColor:secondary,borderDash:[5,4],tension:.25,yAxisID:"r",pointRadius:4}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{labels:{boxWidth:18,font:{family:"Manrope",size:10}}}},scales:{x:{grid:{display:false},ticks:{font:{size:10}}},y:{grid:{color:"#d8dfe3"},ticks:{font:{size:10}}},r:{position:"right",grid:{display:false},ticks:{font:{size:10}}}}}})}
function render(){renderAthletes();renderFilters();renderList();renderDetail()}

function setDrawerStep(step){["day","exercise","values"].forEach(x=>$("#record-step-"+x).classList.toggle("hidden",x!==step));const i={day:0,exercise:1,values:2}[step];$$('.drawer-progress span').forEach((s,n)=>s.classList.toggle("active",n<=i));$("#record-title").textContent=step==="day"?"Выберите день":step==="exercise"?`День: ${state.recordDay}`:"Запишите результат"}
function openDrawer(){state.recordDay=null;state.recordExercise=null;state.recordAthlete=state.athlete;el.drawer.classList.add("open");el.drawer.setAttribute("aria-hidden","false");el.backdrop.classList.remove("hidden");document.body.style.overflow="hidden";setDrawerStep("day");renderAthletes()}
function closeDrawer(){el.drawer.classList.remove("open");el.drawer.setAttribute("aria-hidden","true");el.backdrop.classList.add("hidden");document.body.style.overflow=""}
function planExercises(day){const groups=day==="Ноги"?["Ноги","Корпус"]:["Спина","Грудь","Плечи","Трапеции"];return state.exercises.filter(e=>groups.includes(e.muscle_group))}
function latestFor(exerciseId,athleteSlug=state.athlete){return [...state.sets].filter(s=>s.exercise_id===exerciseId&&s.athletes?.slug===athleteSlug).sort((a,b)=>new Date(b.workouts.performed_at)-new Date(a.workouts.performed_at))[0]}
function renderRecordExercises(){el.recordExercises.innerHTML=planExercises(state.recordDay).map(e=>{const last=latestFor(e.id);return `<button class="exercise-tile" data-record-exercise="${e.id}" type="button"><img src="${imageFor(e)}" alt="${escapeHtml(e.name)}"><span><strong>${escapeHtml(e.name)}</strong><small>${last?`Цель: ${escapeHtml(last.next_step||resultLabel(last))}`:"Нет записей"}</small></span><span class="material-symbols-rounded">chevron_right</span></button>`}).join("");$$('[data-record-exercise]').forEach(b=>b.onclick=()=>selectRecordExercise(b.dataset.recordExercise))}
function selectRecordExercise(id){state.recordExercise=state.exercises.find(e=>e.id===id);const last=latestFor(id,state.recordAthlete);$("#record-selected").innerHTML=`<img src="${imageFor(state.recordExercise)}" alt="${escapeHtml(state.recordExercise.name)}"><div><h3>${escapeHtml(state.recordExercise.name)}</h3><p>${last?`Следующая цель: ${escapeHtml(last.next_step||resultLabel(last))}`:"Первый результат"}</p></div>`;const assisted=state.recordExercise.image_slug==="assisted-pullup";$("#weight-label").textContent=assisted?"Помощь, кг":"Вес, кг";$("#record-weight").value=last?Number(last.assistance_kg??last.weight_kg):0;$("#record-reps").value=last?.reps||10;$("#record-comment").value="";setDrawerStep("values");renderAthletes()}
function nextTarget(weight,reps,assisted){if(assisted)return `${String(weight).replace("-","−")} кг × ${Math.min(reps+2,15)}–${Math.min(reps+4,18)}`;return reps>=15?`${weight+5} кг × 10–12`:`${weight} кг × ${reps+1}–${Math.min(reps+3,15)}`}
async function saveRecord(event){event.preventDefault();const button=$("#save-record"),weight=Number($("#record-weight").value),reps=Number($("#record-reps").value),athlete=state.athletes.find(a=>a.slug===state.recordAthlete),assisted=state.recordExercise.image_slug==="assisted-pullup";if(previewMode){closeDrawer();showToast(`${athlete.name}: ${state.recordExercise.name} — пример записи`);return}button.disabled=true;message(el.recordMessage,"Сохраняю…");const w=await db.from("workouts").insert({performed_at:new Date().toISOString(),day_type:state.recordDay}).select("id").single();let error=w.error;if(!error){const row={workout_id:w.data.id,athlete_id:athlete.id,exercise_id:state.recordExercise.id,set_order:1,weight_kg:assisted?0:weight,assistance_kg:assisted?weight:null,reps,is_warmup:false,next_step:nextTarget(weight,reps,assisted),comment:$("#record-comment").value.trim()||null};({error}=await db.from("workout_sets").insert(row))}button.disabled=false;if(error){message(el.recordMessage,error.message,true);return}message(el.recordMessage);await loadData();closeDrawer();showToast(`${athlete.name}: ${state.recordExercise.name} — записано`)}

function openExerciseDialog(){el.exerciseForm.reset();message(el.exerciseMessage);el.exerciseDialog.showModal();setTimeout(()=>$("#new-exercise-name").focus(),0)}
function closeExerciseDialog(){el.exerciseDialog.close();message(el.exerciseMessage)}
async function saveExercise(event){event.preventDefault();const button=$("#save-exercise"),name=$("#new-exercise-name").value.trim(),group=$("#new-exercise-group").value,image_slug=imageSlugForGroup(group);if(!name)return;button.disabled=true;message(el.exerciseMessage,"Добавляю…");let exercise,error;if(previewMode){exercise={id:`custom-${Date.now()}`,name,muscle_group:group,image_slug}}else{const result=await db.from("exercises").insert({name,muscle_group:group,image_slug}).select("id,name,muscle_group,image_slug").single();exercise=result.data;error=result.error}button.disabled=false;if(error){message(el.exerciseMessage,error.code==="23505"?"Такое упражнение уже есть.":error.message,true);return}state.exercises.push(exercise);closeExerciseDialog();renderFilters();openDrawer();state.recordDay=dayForGroup(group);renderRecordExercises();setDrawerStep("exercise");showToast(`${name} добавлено`)}

function bind(){
  $("#today-label").textContent=new Intl.DateTimeFormat("ru-RU",{day:"numeric",month:"long",year:"numeric"}).format(new Date());
  el.authForm.onsubmit=async e=>{e.preventDefault();const b=e.currentTarget.querySelector("button");b.disabled=true;const {error}=await db.auth.signInWithOtp({email:$("#email").value,options:{emailRedirectTo:`${location.origin}${location.pathname}`}});b.disabled=false;message(el.authMessage,error?error.message:"Ссылка отправлена. Проверьте почту.",Boolean(error))};
  $("#sign-out-button").onclick=()=>db.auth.signOut();el.group.onchange=renderList;el.search.oninput=renderList;$("#open-recorder").onclick=openDrawer;$("#close-recorder").onclick=closeDrawer;$("#close-detail").onclick=closeDetail;el.backdrop.onclick=closeDrawer;$("#open-exercise-dialog").onclick=openExerciseDialog;$("#close-exercise-dialog").onclick=closeExerciseDialog;el.exerciseForm.onsubmit=saveExercise;
  $$('.day-card').forEach(b=>b.onclick=()=>{state.recordDay=b.dataset.day;renderRecordExercises();setDrawerStep("exercise")});$("#back-to-day").onclick=()=>setDrawerStep("day");$("#back-to-exercises").onclick=()=>setDrawerStep("exercise");
  $$('.stepper button').forEach(b=>b.onclick=()=>{const input=b.dataset.step==="weight"?$("#record-weight"):$("#record-reps");input.value=Math.max(Number(input.min),Number(input.value||0)+Number(b.dataset.delta))});$("#record-form").onsubmit=saveRecord;
  document.addEventListener("keydown",e=>{if(e.key==="Escape"&&!el.exerciseDialog.open)closeDrawer()});
}
async function sessionChanged(session){if(!session){show("auth");return}show("app");try{await loadData()}catch(error){console.error(error);showToast(`Ошибка базы: ${error.message}`)}}
function loadPreview(){const seed=window.GYM_SEED;state.athletes=seed.athletes.map(a=>({...a,id:a.slug}));const map=new Map();seed.records.forEach(r=>map.set(r[4],{id:r[4],name:r[3],muscle_group:r[2],image_slug:r[4]}));state.exercises=[...map.values()];state.sets=seed.records.map((r,i)=>({id:String(i),workout_id:r[0],athlete_id:r[1],exercise_id:r[4],weight_kg:r[5]??0,assistance_kg:r[6],reps:r[7],next_step:r[9],comment:r[10],workouts:{id:r[0],performed_at:`${r[0]}T12:00:00+02:00`,day_type:r[0]==="2026-08-24"?"Спина":"Ноги"},athletes:state.athletes.find(a=>a.slug===r[1]),exercises:state.exercises.find(e=>e.id===r[4])}));state.athlete="artem";state.exerciseId="leg-curl";show("app");render()}
async function init(){bind();if(previewMode){loadPreview();return}if(!configured||!window.supabase){show("setup");return}db=window.supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY);const {data}=await db.auth.getSession();await sessionChanged(data.session);db.auth.onAuthStateChange((_e,s)=>setTimeout(()=>sessionChanged(s),0))}
init().catch(error=>{console.error(error);show("setup")});
