const cfg=window.GYM_CONFIG??{};
const configured=cfg.SUPABASE_URL&&cfg.SUPABASE_ANON_KEY&&!cfg.SUPABASE_URL.includes("YOUR_PROJECT");
const $=(s)=>document.querySelector(s); const $$=(s)=>[...document.querySelectorAll(s)];
const el={setup:$("#setup-screen"),auth:$("#auth-screen"),app:$("#app-screen"),authForm:$("#auth-form"),authMessage:$("#auth-message"),athletes:$("#athlete-switcher"),group:$("#group-filter"),search:$("#exercise-search"),list:$("#results-list"),detailEmpty:$("#detail-empty"),detail:$("#detail-content"),drawer:$("#record-drawer"),backdrop:$("#drawer-backdrop"),toast:$("#toast"),recordAthletes:$("#record-athletes"),recordExercises:$("#record-exercises"),recordMessage:$("#record-message"),exerciseDialog:$("#exercise-dialog"),exerciseForm:$("#exercise-form"),exerciseMessage:$("#exercise-message"),imageDialog:$("#image-dialog"),imageForm:$("#image-form"),imageMessage:$("#image-message")};
const state={athletes:[],exercises:[],sets:[],athlete:null,exerciseId:null,charts:[],recordDay:null,recordExercise:null,recordAthlete:null,imagePreviewUrl:null,seeded:false};
let db;
const previewMode=new URLSearchParams(location.search).has("preview")&&["localhost","127.0.0.1"].includes(location.hostname);

function show(screen){el.setup.classList.toggle("hidden",screen!=="setup");el.auth.classList.toggle("hidden",screen!=="auth");el.app.classList.toggle("hidden",screen!=="app")}
function message(node,text="",error=false){node.textContent=text;node.classList.toggle("error",error)}
function escapeHtml(v=""){return String(v).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
function dateLabel(v,short=false){return new Intl.DateTimeFormat("ru-RU",short?{day:"2-digit",month:"short"}:{day:"2-digit",month:"short",year:"numeric"}).format(new Date(v))}
function imageFor(exercise){return exercise?.image_url||`./assets/exercises/${exercise?.image_slug||"leg-curl"}.png`}
function dayForGroup(group){return ["Ноги","Корпус"].includes(group)?"Ноги":"Спина"}
function imageSlugForGroup(group){return ({Ноги:"leg-press",Корпус:"ab-crunch",Спина:"seated-row",Грудь:"incline-dumbbell-press",Плечи:"smith-shoulder-press",Трапеции:"shrugs"})[group]||"leg-curl"}
function muscleIcon(group){return ({Ноги:"directions_run",Корпус:"accessibility_new",Спина:"fitness_center",Грудь:"monitor_heart",Плечи:"sports_gymnastics",Трапеции:"exercise"})[group]||"fitness_center"}
function muscleBadge(group){return `<span class="muscle-badge material-symbols-rounded" aria-hidden="true">${muscleIcon(group)}</span>`}
function resultLabel(set){const value=set.assistance_kg!=null?Number(set.assistance_kg):Number(set.weight_kg);return `${String(value).replace("-","−")} × ${set.reps}`}
function personSets(){return state.sets.filter(s=>s.athletes?.slug===state.athlete)}
function sortedHistory(exerciseId){return personSets().filter(s=>s.exercise_id===exerciseId).sort((a,b)=>new Date(a.workouts.performed_at)-new Date(b.workouts.performed_at))}
function latestByExercise(){const map=new Map();[...personSets()].sort((a,b)=>new Date(b.workouts.performed_at)-new Date(a.workouts.performed_at)).forEach(s=>{if(!map.has(s.exercise_id))map.set(s.exercise_id,s)});return [...map.values()]}
function showToast(text){el.toast.textContent=text;el.toast.classList.remove("hidden");setTimeout(()=>el.toast.classList.add("hidden"),2600)}
function applyAthleteTheme(){const isNatasha=state.athlete==="natasha";[el.app,document.body].forEach(node=>{node.classList.toggle("theme-natasha",isNatasha);node.classList.toggle("theme-artem",!isNatasha)});document.documentElement.style.colorScheme="light"}

async function ensureSeed(){
  if(state.athletes.length||!window.GYM_SEED)return;
  const aRes=await db.from("athletes").insert(window.GYM_SEED.athletes).select("id,slug,name"); if(aRes.error)throw aRes.error;
  const unique=new Map();window.GYM_SEED.records.forEach(r=>unique.set(r[4],{name:r[3],muscle_group:r[2],image_slug:r[4]}));
  const eRes=await db.from("exercises").insert([...unique.values()]).select("id,name,muscle_group,image_slug,image_url");if(eRes.error)throw eRes.error;
  const athleteIds=Object.fromEntries(aRes.data.map(a=>[a.slug,a.id]));const exerciseIds=Object.fromEntries(eRes.data.map(e=>[e.image_slug,e.id]));
  for(const date of [...new Set(window.GYM_SEED.records.map(r=>r[0]))]){
    const records=window.GYM_SEED.records.filter(r=>r[0]===date);const dayType=date==="2026-08-24"?"Спина":"Ноги";
    const wRes=await db.from("workouts").insert({performed_at:`${date}T12:00:00+02:00`,day_type:dayType,notes:"Импортировано из тренировочной базы"}).select("id").single();if(wRes.error)throw wRes.error;
    const rows=records.map((r,i)=>({workout_id:wRes.data.id,athlete_id:athleteIds[r[1]],exercise_id:exerciseIds[r[4]],set_order:i+1,weight_kg:r[5]??0,assistance_kg:r[6],reps:r[7],is_warmup:false,next_step:r[9],comment:r[10]||null}));
    const sRes=await db.from("workout_sets").insert(rows);if(sRes.error)throw sRes.error;
  }
  state.seeded=true;
}

async function loadData(){
  const [a,e,s]=await Promise.all([
    db.from("athletes").select("id,slug,name").order("name"),
    db.from("exercises").select("id,name,muscle_group,image_slug,image_url").order("name"),
    db.from("workout_sets").select("id,workout_id,athlete_id,exercise_id,set_order,weight_kg,assistance_kg,reps,next_step,comment,workouts(id,performed_at,day_type),athletes(id,slug,name),exercises(id,name,muscle_group,image_slug,image_url)")
  ]);if(a.error)throw a.error;if(e.error)throw e.error;if(s.error)throw s.error;
  state.athletes=a.data??[];state.exercises=e.data??[];state.sets=(s.data??[]).filter(x=>x.athletes&&x.exercises&&x.workouts);
  if(!state.athletes.length){await ensureSeed();return loadData()}
  state.athlete=state.athlete&&state.athletes.some(a=>a.slug===state.athlete)?state.athlete:(state.athletes.find(a=>a.slug==="artem")?.slug||state.athletes[0].slug);
  if(!state.exerciseId)state.exerciseId=latestByExercise()[0]?.exercise_id||null;render();
}

function renderAthletes(){applyAthleteTheme();const html=state.athletes.map(a=>`<button class="${a.slug===state.athlete?"active":""}" data-athlete="${a.slug}" type="button">${escapeHtml(a.name)}</button>`).join("");el.athletes.innerHTML=html;el.recordAthletes.innerHTML=state.athletes.map(a=>`<button class="${a.slug===state.recordAthlete?"active":""}" data-record-athlete="${a.slug}" type="button">${escapeHtml(a.name)}</button>`).join("");$$('[data-athlete]').forEach(b=>b.onclick=()=>{state.athlete=b.dataset.athlete;state.exerciseId=latestByExercise()[0]?.exercise_id||null;render()});$$('[data-record-athlete]').forEach(b=>b.onclick=()=>{state.recordAthlete=b.dataset.recordAthlete;renderAthletes()})}
function changeLabel(history){if(history.length<2)return {text:"Первая запись",kind:"wait",icon:"horizontal_rule"};const prev=history.at(-2),last=history.at(-1);const prevLoad=prev.assistance_kg??prev.weight_kg,lastLoad=last.assistance_kg??last.weight_kg;if(Number(lastLoad)!==Number(prevLoad)){const delta=Number(lastLoad)-Number(prevLoad);return {text:`${delta>0?"+":""}${String(delta).replace("-","−")} кг`,kind:"good",icon:"trending_up"}}const delta=last.reps-prev.reps;return delta>0?{text:`+${delta} повт.`,kind:"good",icon:"trending_up"}:{text:"Без изменений",kind:"wait",icon:"trending_flat"}}
function renderFilters(){const groups=[...new Set(state.exercises.map(e=>e.muscle_group).filter(Boolean))].sort();const current=el.group.value;el.group.innerHTML='<option value="all">Все группы</option>'+groups.map(g=>`<option value="${escapeHtml(g)}">${escapeHtml(g)}</option>`).join("");el.group.value=groups.includes(current)?current:"all"}
function renderList(){let rows=latestByExercise();const q=el.search.value.trim().toLowerCase(),group=el.group.value;rows=rows.filter(s=>(group==="all"||s.exercises.muscle_group===group)&&(!q||s.exercises.name.toLowerCase().includes(q)));if(!rows.length){el.list.innerHTML='<div class="empty-list">Нет результатов по выбранному фильтру</div>';return}el.list.innerHTML=rows.map(s=>{const h=sortedHistory(s.exercise_id),delta=changeLabel(h),groupName=s.exercises.muscle_group||"";return `<button class="result-row ${s.exercise_id===state.exerciseId?"selected":""}" data-exercise="${s.exercise_id}" type="button"><span class="exercise-cell"><img src="${imageFor(s.exercises)}" alt="${escapeHtml(s.exercises.name)}"><span class="exercise-copy"><span class="exercise-name-line">${muscleBadge(groupName)}<strong>${escapeHtml(s.exercises.name)}</strong></span><small>${escapeHtml(groupName)}</small></span></span><span class="primary-result">${resultLabel(s)}</span><span>${dateLabel(s.workouts.performed_at,true)}</span><span class="target">${escapeHtml(s.next_step||"Повторить результат")}</span><span class="delta ${delta.kind}"><span class="material-symbols-rounded">${delta.icon}</span>${delta.text}</span></button>`}).join("");$$('[data-exercise]').forEach(b=>b.onclick=()=>{state.exerciseId=b.dataset.exercise;renderList();renderDetail();if(matchMedia("(max-width: 980px)").matches){el.app.classList.add("detail-open");$("#detail-pane").classList.add("mobile-open");document.body.style.overflow="hidden"}})}
function closeDetail(){$("#detail-pane").classList.remove("mobile-open");el.app.classList.remove("detail-open");document.body.style.overflow=""}
function estimatedMax(set){return Number(set.weight_kg||0)*(1+Number(set.reps||0)/30)}
function bestSessionPoints(history,assisted){const sessions=new Map();history.forEach(set=>{const key=set.workout_id||set.workouts.id,current=sessions.get(key),rank=assisted?Number(set.assistance_kg??-9999)*1000+Number(set.reps):estimatedMax(set);if(!current||rank>current.rank)sessions.set(key,{set,rank})});return [...sessions.values()].map(x=>x.set).sort((a,b)=>new Date(a.workouts.performed_at)-new Date(b.workouts.performed_at))}
function progressPercent(points,assisted){if(points.length<2)return 0;const first=points[0],last=points.at(-1);if(assisted){const firstLoad=Number(first.assistance_kg??0),lastLoad=Number(last.assistance_kg??0);if(firstLoad!==lastLoad)return Math.round((lastLoad-firstLoad)/Math.max(1,Math.abs(firstLoad))*100);return Math.round((Number(last.reps)-Number(first.reps))/Math.max(1,Number(first.reps))*100)}const firstMax=estimatedMax(first),lastMax=estimatedMax(last);return firstMax?Math.round((lastMax-firstMax)/firstMax*100):0}
function destroyCharts(){state.charts.forEach(chart=>chart.destroy());state.charts=[]}
function makeTrendChart(canvas,labels,data,color,unit=""){const values=data.map(Number),single=values.length===1;return new Chart(canvas,{type:"line",data:{labels,datasets:[{data:values,borderColor:color,backgroundColor:`${color}1f`,fill:true,tension:.28,pointRadius:single?5:3.5,pointHoverRadius:6,borderWidth:2.5}]},options:{responsive:true,maintainAspectRatio:false,interaction:{intersect:false,mode:"index"},plugins:{legend:{display:false},tooltip:{displayColors:false,callbacks:{label:ctx=>`${ctx.parsed.y}${unit}`}}},scales:{x:{grid:{display:false},ticks:{font:{family:"Manrope",size:10},maxRotation:0,autoSkip:true,maxTicksLimit:5}},y:{grace:"15%",grid:{color:"#e5eaed"},ticks:{font:{family:"Manrope",size:10},maxTicksLimit:5}}}}})}
function renderDetail(){const history=sortedHistory(state.exerciseId);if(!history.length){el.detailEmpty.classList.remove("hidden");el.detail.classList.add("hidden");destroyCharts();return}el.detailEmpty.classList.add("hidden");el.detail.classList.remove("hidden");const latest=history.at(-1),exercise=latest.exercises,assisted=history.some(s=>s.assistance_kg!=null),points=bestSessionPoints(history,assisted),progress=progressPercent(points,assisted),loads=points.map(s=>Number(s.assistance_kg??s.weight_kg)),reps=points.map(s=>Number(s.reps)),maxes=points.map(estimatedMax),bestLoad=assisted?(loads.every(v=>v>=0)?Math.min(...loads):Math.max(...loads)):Math.max(...loads),bestIndex=assisted?loads.indexOf(bestLoad):maxes.indexOf(Math.max(...maxes)),bestSet=points[Math.max(0,bestIndex)];$("#detail-group").textContent=exercise.muscle_group||"Упражнение";$("#detail-muscle-icon").textContent=muscleIcon(exercise.muscle_group);$("#detail-name").textContent=exercise.name;$("#detail-result").textContent=resultLabel(latest);$("#detail-date").textContent=dateLabel(latest.workouts.performed_at);$("#detail-target").textContent=latest.next_step||"Повторить результат";$("#detail-progress").textContent=`${progress>0?"+":""}${progress}%`;$("#detail-progress").className=progress>0?"positive":progress<0?"negative":"";$("#detail-sessions").textContent=`${points.length} ${points.length===1?"тренировка":"тренировок"}`;$("#best-load-label").textContent=assisted?"Минимальная помощь":"Лучший вес";$("#best-load").textContent=`${String(bestLoad).replace("-","−")} кг`;$("#best-reps").textContent=Math.max(...reps);$("#estimated-max-card").querySelector("span").textContent=assisted?"Лучший подход":"Расчётный 1ПМ";$("#estimated-max").textContent=assisted?resultLabel(bestSet):`${Math.round(Math.max(...maxes)*10)/10} кг`;$("#load-chart-title").textContent=assisted?"Помощь, кг":"Рабочий вес";$("#strength-chart-card").classList.toggle("hidden",assisted);$("#history-list").innerHTML=[...history].reverse().map(s=>`<div class="history-row"><span>${dateLabel(s.workouts.performed_at,true)}</span><strong>${resultLabel(s)}</strong><small>${escapeHtml(s.comment||s.next_step||"")}</small></div>`).join("");destroyCharts();const labels=points.map(s=>dateLabel(s.workouts.performed_at,true)),primary=getComputedStyle(el.app).getPropertyValue("--theme-accent").trim()||"#2e6687";state.charts.push(makeTrendChart($("#load-chart"),labels,loads,primary," кг"));state.charts.push(makeTrendChart($("#reps-chart"),labels,reps,"#27864b"," повт."));if(!assisted)state.charts.push(makeTrendChart($("#strength-chart"),labels,maxes,"#6f61a8"," кг"))}
function render(){renderAthletes();renderFilters();renderList();renderDetail()}

function setDrawerStep(step){["day","exercise","values"].forEach(x=>$("#record-step-"+x).classList.toggle("hidden",x!==step));const i={day:0,exercise:1,values:2}[step];$$('.drawer-progress span').forEach((s,n)=>s.classList.toggle("active",n<=i));$("#record-title").textContent=step==="day"?"Выберите день":step==="exercise"?`День: ${state.recordDay}`:"Запишите результат"}
function openDrawer(){state.recordDay=null;state.recordExercise=null;state.recordAthlete=state.athlete;el.drawer.classList.add("open");el.drawer.setAttribute("aria-hidden","false");el.backdrop.classList.remove("hidden");document.body.style.overflow="hidden";setDrawerStep("day");renderAthletes()}
function closeDrawer(){el.drawer.classList.remove("open");el.drawer.setAttribute("aria-hidden","true");el.backdrop.classList.add("hidden");document.body.style.overflow=""}
function planExercises(day){const groups=day==="Ноги"?["Ноги","Корпус"]:["Спина","Грудь","Плечи","Трапеции"];return state.exercises.filter(e=>groups.includes(e.muscle_group))}
function latestFor(exerciseId,athleteSlug=state.athlete){return [...state.sets].filter(s=>s.exercise_id===exerciseId&&s.athletes?.slug===athleteSlug).sort((a,b)=>new Date(b.workouts.performed_at)-new Date(a.workouts.performed_at))[0]}
function renderRecordExercises(){el.recordExercises.innerHTML=planExercises(state.recordDay).map(e=>{const last=latestFor(e.id);return `<button class="exercise-tile" data-record-exercise="${e.id}" type="button"><img src="${imageFor(e)}" alt="${escapeHtml(e.name)}"><span><span class="exercise-name-line">${muscleBadge(e.muscle_group)}<strong>${escapeHtml(e.name)}</strong></span><small>${last?`Цель: ${escapeHtml(last.next_step||resultLabel(last))}`:"Нет записей"}</small></span><span class="material-symbols-rounded">chevron_right</span></button>`}).join("");$$('[data-record-exercise]').forEach(b=>b.onclick=()=>selectRecordExercise(b.dataset.recordExercise))}
function selectRecordExercise(id){state.recordExercise=state.exercises.find(e=>e.id===id);const last=latestFor(id,state.recordAthlete);$("#record-selected").innerHTML=`<img src="${imageFor(state.recordExercise)}" alt="${escapeHtml(state.recordExercise.name)}"><div><span class="exercise-name-line">${muscleBadge(state.recordExercise.muscle_group)}<h3>${escapeHtml(state.recordExercise.name)}</h3></span><p>${last?`Следующая цель: ${escapeHtml(last.next_step||resultLabel(last))}`:"Первый результат"}</p></div>`;const assisted=state.recordExercise.image_slug==="assisted-pullup";$("#weight-label").textContent=assisted?"Помощь, кг":"Вес, кг";$("#record-weight").value=last?Number(last.assistance_kg??last.weight_kg):0;$("#record-reps").value=last?.reps||10;$("#record-comment").value="";setDrawerStep("values");renderAthletes()}
function nextTarget(weight,reps,assisted){if(assisted)return `${String(weight).replace("-","−")} кг × ${Math.min(reps+2,15)}–${Math.min(reps+4,18)}`;return reps>=15?`${weight+5} кг × 10–12`:`${weight} кг × ${reps+1}–${Math.min(reps+3,15)}`}
async function saveRecord(event){event.preventDefault();const button=$("#save-record"),weight=Number($("#record-weight").value),reps=Number($("#record-reps").value),athlete=state.athletes.find(a=>a.slug===state.recordAthlete),assisted=state.recordExercise.image_slug==="assisted-pullup";if(previewMode){closeDrawer();showToast(`${athlete.name}: ${state.recordExercise.name} — пример записи`);return}button.disabled=true;message(el.recordMessage,"Сохраняю…");const w=await db.from("workouts").insert({performed_at:new Date().toISOString(),day_type:state.recordDay}).select("id").single();let error=w.error;if(!error){const row={workout_id:w.data.id,athlete_id:athlete.id,exercise_id:state.recordExercise.id,set_order:1,weight_kg:assisted?0:weight,assistance_kg:assisted?weight:null,reps,is_warmup:false,next_step:nextTarget(weight,reps,assisted),comment:$("#record-comment").value.trim()||null};({error}=await db.from("workout_sets").insert(row))}button.disabled=false;if(error){message(el.recordMessage,error.message,true);return}message(el.recordMessage);await loadData();closeDrawer();showToast(`${athlete.name}: ${state.recordExercise.name} — записано`)}

function openExerciseDialog(){el.exerciseForm.reset();message(el.exerciseMessage);el.exerciseDialog.showModal();setTimeout(()=>$("#new-exercise-name").focus(),0)}
function closeExerciseDialog(){el.exerciseDialog.close();message(el.exerciseMessage)}
async function saveExercise(event){event.preventDefault();const button=$("#save-exercise"),name=$("#new-exercise-name").value.trim(),group=$("#new-exercise-group").value,image_slug=imageSlugForGroup(group);if(!name)return;button.disabled=true;message(el.exerciseMessage,"Добавляю…");let exercise,error;if(previewMode){exercise={id:`custom-${Date.now()}`,name,muscle_group:group,image_slug,image_url:null}}else{const result=await db.from("exercises").insert({name,muscle_group:group,image_slug}).select("id,name,muscle_group,image_slug,image_url").single();exercise=result.data;error=result.error}button.disabled=false;if(error){message(el.exerciseMessage,error.code==="23505"?"Такое упражнение уже есть.":error.message,true);return}state.exercises.push(exercise);closeExerciseDialog();renderFilters();openDrawer();state.recordDay=dayForGroup(group);renderRecordExercises();setDrawerStep("exercise");showToast(`${name} добавлено`)}

function currentExercise(){return state.exercises.find(e=>e.id===state.exerciseId)}
function syncExerciseImage(exerciseId,imageUrl){const exercise=state.exercises.find(e=>e.id===exerciseId);if(exercise)exercise.image_url=imageUrl;state.sets.forEach(set=>{if(set.exercise_id===exerciseId&&set.exercises)set.exercises.image_url=imageUrl})}
function closeImageDialog(){if(el.imageDialog.open)el.imageDialog.close();message(el.imageMessage);if(state.imagePreviewUrl){URL.revokeObjectURL(state.imagePreviewUrl);state.imagePreviewUrl=null}}
function openImageDialog(){const exercise=currentExercise();if(!exercise)return;el.imageForm.reset();message(el.imageMessage);$("#exercise-image-preview").src=imageFor(exercise);el.imageDialog.showModal()}
function previewExerciseImage(){const file=$("#exercise-image-file").files[0];if(!file)return;if(!file.type.startsWith("image/")){message(el.imageMessage,"Выберите изображение.",true);return}if(file.size>8*1024*1024){message(el.imageMessage,"Файл должен быть меньше 8 МБ.",true);return}if(state.imagePreviewUrl)URL.revokeObjectURL(state.imagePreviewUrl);state.imagePreviewUrl=URL.createObjectURL(file);$("#exercise-image-preview").src=state.imagePreviewUrl;message(el.imageMessage)}
async function optimizedImageBlob(file){const sourceUrl=URL.createObjectURL(file);try{const image=await new Promise((resolve,reject)=>{const node=new Image();node.onload=()=>resolve(node);node.onerror=()=>reject(new Error("Не удалось прочитать изображение"));node.src=sourceUrl});const maxSide=1200,scale=Math.min(1,maxSide/Math.max(image.naturalWidth,image.naturalHeight)),canvas=document.createElement("canvas");canvas.width=Math.max(1,Math.round(image.naturalWidth*scale));canvas.height=Math.max(1,Math.round(image.naturalHeight*scale));canvas.getContext("2d").drawImage(image,0,0,canvas.width,canvas.height);return await new Promise(resolve=>canvas.toBlob(blob=>resolve(blob||file),"image/webp",.84))}finally{URL.revokeObjectURL(sourceUrl)}}
async function saveExerciseImage(event){event.preventDefault();const exercise=currentExercise(),file=$("#exercise-image-file").files[0],button=$("#save-exercise-image");if(!exercise||!file){message(el.imageMessage,"Сначала выберите изображение.",true);return}button.disabled=true;message(el.imageMessage,"Подготавливаю изображение…");try{const blob=await optimizedImageBlob(file);if(blob.size>2*1024*1024)throw new Error("После обработки файл больше 2 МБ. Выберите другое изображение.");if(previewMode){const localUrl=URL.createObjectURL(blob);syncExerciseImage(exercise.id,localUrl)}else{const {data:userData,error:userError}=await db.auth.getUser();if(userError||!userData.user)throw userError||new Error("Нужно войти заново");const path=`${userData.user.id}/${exercise.id}-${Date.now()}.webp`,bucket=db.storage.from("exercise-images"),upload=await bucket.upload(path,blob,{contentType:"image/webp",cacheControl:"3600",upsert:true});if(upload.error)throw upload.error;const publicUrl=bucket.getPublicUrl(path).data.publicUrl;const updated=await db.from("exercises").update({image_url:publicUrl}).eq("id",exercise.id);if(updated.error)throw updated.error;syncExerciseImage(exercise.id,`${publicUrl}?v=${Date.now()}`)}closeImageDialog();renderList();renderDetail();showToast("Изображение упражнения обновлено")}catch(error){message(el.imageMessage,error.message,true)}finally{button.disabled=false}}
async function resetExerciseImage(){const exercise=currentExercise();if(!exercise)return;const button=$("#reset-exercise-image");button.disabled=true;message(el.imageMessage,"Возвращаю стандартное изображение…");try{if(!previewMode){const updated=await db.from("exercises").update({image_url:null}).eq("id",exercise.id);if(updated.error)throw updated.error}syncExerciseImage(exercise.id,null);closeImageDialog();renderList();renderDetail();showToast("Стандартное изображение восстановлено")}catch(error){message(el.imageMessage,error.message,true)}finally{button.disabled=false}}

function bind(){
  $("#today-label").textContent=new Intl.DateTimeFormat("ru-RU",{day:"numeric",month:"long",year:"numeric"}).format(new Date());
  el.authForm.onsubmit=async e=>{e.preventDefault();const b=e.currentTarget.querySelector("button");b.disabled=true;const {error}=await db.auth.signInWithOtp({email:$("#email").value,options:{emailRedirectTo:`${location.origin}${location.pathname}`}});b.disabled=false;message(el.authMessage,error?error.message:"Ссылка отправлена. Проверьте почту.",Boolean(error))};
  $("#sign-out-button").onclick=()=>db.auth.signOut();el.group.onchange=renderList;el.search.oninput=renderList;$("#open-recorder").onclick=openDrawer;$("#close-recorder").onclick=closeDrawer;$("#close-detail").onclick=closeDetail;el.backdrop.onclick=closeDrawer;$("#open-exercise-dialog").onclick=openExerciseDialog;$("#close-exercise-dialog").onclick=closeExerciseDialog;el.exerciseForm.onsubmit=saveExercise;$("#change-exercise-image").onclick=openImageDialog;$("#close-image-dialog").onclick=closeImageDialog;$("#exercise-image-file").onchange=previewExerciseImage;$("#reset-exercise-image").onclick=resetExerciseImage;el.imageForm.onsubmit=saveExerciseImage;
  $$('.day-card').forEach(b=>b.onclick=()=>{state.recordDay=b.dataset.day;renderRecordExercises();setDrawerStep("exercise")});$("#back-to-day").onclick=()=>setDrawerStep("day");$("#back-to-exercises").onclick=()=>setDrawerStep("exercise");
  $$('.stepper button').forEach(b=>b.onclick=()=>{const input=b.dataset.step==="weight"?$("#record-weight"):$("#record-reps");input.value=Math.max(Number(input.min),Number(input.value||0)+Number(b.dataset.delta))});$("#record-form").onsubmit=saveRecord;
  document.addEventListener("keydown",e=>{if(e.key==="Escape"&&!el.exerciseDialog.open&&!el.imageDialog.open)closeDrawer()});
}
async function sessionChanged(session){if(!session){show("auth");return}show("app");try{await loadData()}catch(error){console.error(error);showToast(`Ошибка базы: ${error.message}`)}}
function loadPreview(){const seed=window.GYM_SEED;state.athletes=seed.athletes.map(a=>({...a,id:a.slug}));const map=new Map();seed.records.forEach(r=>map.set(r[4],{id:r[4],name:r[3],muscle_group:r[2],image_slug:r[4],image_url:null}));state.exercises=[...map.values()];state.sets=seed.records.map((r,i)=>({id:String(i),workout_id:r[0],athlete_id:r[1],exercise_id:r[4],weight_kg:r[5]??0,assistance_kg:r[6],reps:r[7],next_step:r[9],comment:r[10],workouts:{id:r[0],performed_at:`${r[0]}T12:00:00+02:00`,day_type:r[0]==="2026-08-24"?"Спина":"Ноги"},athletes:state.athletes.find(a=>a.slug===r[1]),exercises:state.exercises.find(e=>e.id===r[4])}));state.athlete="artem";state.exerciseId="leg-curl";show("app");render()}
async function init(){bind();if(previewMode){loadPreview();return}if(!configured||!window.supabase){show("setup");return}db=window.supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY);const {data}=await db.auth.getSession();await sessionChanged(data.session);db.auth.onAuthStateChange((_e,s)=>setTimeout(()=>sessionChanged(s),0))}
init().catch(error=>{console.error(error);show("setup")});
